server:
  port: 9001

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: "carAppGroup"
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

carApp:
  policies:
    distanceKmUntilMaintenanceNeeded: 10000.0
